### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by rangertaha** [cybint/urlinsane#61]
We need logging to troubleshoot connection issues. However, we don't want the logging to interfere with standard output. 

FLAGS:
   --log.enabled (False)
   --log.filename (urlinsane.log)
   --log.level (ERROR)

**Comment by jubairsaidi** [comment]
for websocket use, you can probably just send the error in a message with it's own "error" structure so I can handle it (i.e. collect the errors for display on the UI)

**Comment by rangertaha** [comment]
> for websocket use, you can probably just send the error in a message with it's own "error" structure so I can handle it (i.e. collect the errors for display on the UI)

Good idea, will do
